"""Version 1 — the job store on PostgreSQL (ADR-0045, worker lease columns of
ADR-0046), as commit 5e2c2f8 created it on 2026-09-16.  The tables the
later versions extend are created here without their later columns."""
from api.migrations import Migration, columns_exist, indexes_exist, tables_exist

_TABLES = ("jobs", "entities", "relationships", "progress_events", "relationship_policy",
           "report_figures", "figure_reads", "cve_cache")


def _applied(conn) -> bool:
    return (tables_exist(conn, *_TABLES)
            and columns_exist(conn, "jobs", "worker_id", "heartbeat_at")
            and indexes_exist(conn, "idx_entities_job", "idx_relationships_job", "idx_progress_job",
                              "idx_report_figures_span"))


MIGRATION = Migration(
    version=1,
    name="job_store",
    store="jobs",
    description="Job store tables: jobs, entities, relationships, progress, policy, figures, CVE cache",
    is_applied=_applied,
    statements=(
        """CREATE TABLE IF NOT EXISTS jobs (
    id TEXT PRIMARY KEY,
    original_filename TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'uploaded',
    report_text TEXT,
    bundle_json TEXT,
    llm_result_json TEXT,
    tlp_level TEXT,
    pap_level TEXT,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    run_config_json TEXT,
    worker_id TEXT,
    heartbeat_at TEXT
)""",
        # ADR-0046 lease columns, for a store created by ADR-0045 before them.
        "ALTER TABLE jobs ADD COLUMN IF NOT EXISTS worker_id TEXT",
        "ALTER TABLE jobs ADD COLUMN IF NOT EXISTS heartbeat_at TEXT",
        """CREATE TABLE IF NOT EXISTS entities (
    id TEXT PRIMARY KEY,
    job_id TEXT NOT NULL REFERENCES jobs(id) ON DELETE CASCADE,
    value TEXT NOT NULL,
    entity_type TEXT NOT NULL,
    context TEXT DEFAULT '',
    confidence DOUBLE PRECISION DEFAULT 1.0,
    mitre_id TEXT,
    accepted INTEGER,
    source TEXT DEFAULT 'auto',
    evidence_text TEXT,
    evidence_label TEXT,
    evidence_start INTEGER,
    evidence_end INTEGER
)""",
        """CREATE TABLE IF NOT EXISTS relationships (
    id TEXT PRIMARY KEY,
    job_id TEXT NOT NULL REFERENCES jobs(id) ON DELETE CASCADE,
    source_value TEXT NOT NULL,
    relationship_type TEXT NOT NULL,
    target_value TEXT NOT NULL,
    confidence DOUBLE PRECISION DEFAULT 0.8,
    accepted INTEGER DEFAULT 1,
    evidence_text TEXT,
    evidence_label TEXT DEFAULT 'reported'
)""",
        """CREATE TABLE IF NOT EXISTS progress_events (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_id TEXT NOT NULL,
    event_type TEXT NOT NULL,
    data TEXT NOT NULL,
    created_at TEXT NOT NULL
)""",
        "CREATE INDEX IF NOT EXISTS idx_entities_job ON entities(job_id)",
        "CREATE INDEX IF NOT EXISTS idx_relationships_job ON relationships(job_id)",
        "CREATE INDEX IF NOT EXISTS idx_progress_job ON progress_events(job_id)",
        # Relationship policy: a single-row JSON store (id always = 1).
        """CREATE TABLE IF NOT EXISTS relationship_policy (
    id INTEGER PRIMARY KEY DEFAULT 1,
    policy_json TEXT NOT NULL DEFAULT '{}'
)""",
        # ADR-0032: provenance for figure-derived evidence.
        """CREATE TABLE IF NOT EXISTS report_figures (
    id TEXT PRIMARY KEY,
    job_id TEXT NOT NULL REFERENCES jobs(id) ON DELETE CASCADE,
    ordinal INTEGER NOT NULL,
    page INTEGER NOT NULL,
    bbox TEXT NOT NULL,
    kind TEXT NOT NULL,
    char_start INTEGER NOT NULL,
    char_end INTEGER NOT NULL,
    provider TEXT NOT NULL DEFAULT '',
    model TEXT NOT NULL DEFAULT '',
    sha256 TEXT NOT NULL DEFAULT '',
    UNIQUE (job_id, ordinal)
)""",
        "CREATE INDEX IF NOT EXISTS idx_report_figures_span ON report_figures(job_id, char_start)",
        # ADR-0033: the figure read cache, keyed on the crop bytes.
        """CREATE TABLE IF NOT EXISTS figure_reads (
    sha256 TEXT NOT NULL,
    model TEXT NOT NULL,
    prompt_version INTEGER NOT NULL,
    read_json TEXT NOT NULL,
    created_at TEXT NOT NULL,
    PRIMARY KEY (sha256, model, prompt_version)
)""",
        # CVE metadata fetched from CIRCL; a row with NULL description AND
        # cvss_score is a remembered miss.
        """CREATE TABLE IF NOT EXISTS cve_cache (
    cve_id TEXT PRIMARY KEY,
    description TEXT,
    cvss_score DOUBLE PRECISION,
    cvss_vector TEXT,
    fetched_at TEXT NOT NULL
)""",
    ),
)
