"""Version 6 — who decided every review decision (ADR-0058, commit 973da60).

Columns that record the origin of `accepted`, a backfill that marks the
decisions made before them as `legacy` (they cannot be attributed: the review
page wrote its auto-accepts through the same PATCH an analyst used), and the
`review_decisions` journal, one row per change of `accepted`.  The journal is
created with the cascading key it had at the time; version 7 drops it."""
from api.migrations import Migration, columns_exist, indexes_exist, table_exists


def _applied(conn) -> bool:
    if not (columns_exist(conn, "entities", "decision_origin", "decided_at", "policy_version", "control_sample")
            and columns_exist(conn, "relationships", "decision_origin", "decided_at", "policy_version")
            and table_exists(conn, "review_decisions")
            and indexes_exist(conn, "idx_review_decisions_job", "idx_review_decisions_target")):
        return False
    # The backfill too: no decision left without an origin.
    for table in ("entities", "relationships"):
        if conn.execute(f"SELECT 1 FROM {table} WHERE accepted IS NOT NULL AND decision_origin IS NULL "
                        "LIMIT 1").fetchone() is not None:
            return False
    return True


MIGRATION = Migration(
    version=6,
    name="decision_provenance",
    store="jobs",
    description="decision_origin/decided_at/policy_version on entities and relationships, "
                "control_sample on entities, legacy backfill, review_decisions journal",
    is_applied=_applied,
    statements=(
        "ALTER TABLE entities ADD COLUMN IF NOT EXISTS decision_origin TEXT",
        "ALTER TABLE entities ADD COLUMN IF NOT EXISTS decided_at TEXT",
        "ALTER TABLE entities ADD COLUMN IF NOT EXISTS policy_version TEXT",
        "ALTER TABLE entities ADD COLUMN IF NOT EXISTS control_sample INTEGER NOT NULL DEFAULT 0",
        "ALTER TABLE relationships ADD COLUMN IF NOT EXISTS decision_origin TEXT",
        "ALTER TABLE relationships ADD COLUMN IF NOT EXISTS decided_at TEXT",
        "ALTER TABLE relationships ADD COLUMN IF NOT EXISTS policy_version TEXT",
        "UPDATE entities SET decision_origin='legacy' WHERE accepted IS NOT NULL AND decision_origin IS NULL",
        "UPDATE relationships SET decision_origin='legacy' WHERE accepted IS NOT NULL AND decision_origin IS NULL",
        """CREATE TABLE IF NOT EXISTS review_decisions (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_id TEXT NOT NULL REFERENCES jobs(id) ON DELETE CASCADE,
    target_kind TEXT NOT NULL,
    target_id TEXT NOT NULL,
    previous INTEGER,
    accepted INTEGER,
    origin TEXT NOT NULL,
    actor TEXT,
    policy_version TEXT,
    created_at TEXT NOT NULL
)""",
        "CREATE INDEX IF NOT EXISTS idx_review_decisions_job ON review_decisions(job_id)",
        "CREATE INDEX IF NOT EXISTS idx_review_decisions_target ON review_decisions(target_id)",
    ),
)
